### ISSUE TITLE
The segments_ts.txt and segments_stats.pkl are not found in segmentation directory

### ISSUE THREAD

**Issue by Bo396543018** [Darshansingh11/AVLectures#1] opened 2023-01-24 09:28 UTC
Thank you for your great work.
When I downloaded  dataset about Courses with Segmentation (CwS),  There are no file names called  segments_ts.txt and segments_stats.pkl.  Where can I get these files?

By the way, when will the code be open source?

**Comment by Darshansingh11** [comment] 2023-01-28 12:32
Hi @Bo396543018,
Thank you for your interest in our work. Thanks for pointing out that the `segments_ts.txt` and `segments_stats.pkl` files are missing from the segmentation directory. They will be added to the segmentation directory within two days. 
The code will be released soon (most likely within a couple of weeks).

**Comment by Darshansingh11** [comment] 2023-02-10 07:22
Hi @Bo396543018,
The issue is resolved now. All the files are now up. I will be closing this issue. Thanks!

**Closed as completed by Darshansingh11** 2023-02-10 07:22 UTC
